### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by Cherrysaber** [p4gefau1t/trojan-r#4]
本地回环压力测试，server和clinet选择log等级不一样，有概率出现内存泄漏
![TIM截图20201217002813](https://user-images.githubusercontent.com/33094695/102382023-e7ec4500-4004-11eb-9026-818759ab60c1.jpg)
![TIM截图20201217002827](https://user-images.githubusercontent.com/33094695/102382025-e91d7200-4004-11eb-94a0-293a351a8866.jpg)
复现成功概率大概30%左右吧

**Comment by p4gefau1t** [comment]
我这里的测试似乎不能复现，可以提供一下配置文件吗
