### ISSUE TITLE
作者你好,我发现谷歌的云端硬盘上传大文件无法成功

### ISSUE THREAD

**Issue by WifiFly** [p4gefau1t/trojan-r#6]
如题

**Comment by NetHeritage** [comment]
这与trojan-r的关系是？

**Comment by WifiFly** [comment]
> 这与trojan-r的关系是？

我用trojan-r做的代理,然后上传文件，结果进度条一直是卡住的

**Comment by Xx0101** [comment]
作者大佬,您试试在mac电脑试试在这个网站上传10-40M的图片看看

**Comment by akayj** [comment]
> 

测试了下， 上传一个8M的文件，没有问题。所以你可以看看trojan-r的日志呢
