### ISSUE TITLE
作者老师你好，请问froward.toml怎么配置

### ISSUE THREAD

**Issue by 669800** [p4gefau1t/trojan-r#8]
本地必须用sock5才能访问外网，trojan-r必须通过这个socks5才能工作。我该怎么写配置文件。

**Comment by GickThomas** [comment]
参考：https://hogwarts.blog/archives/94.html

**Comment by 669800** [comment]
> 参考：https://hogwarts.blog/archives/94.html

``02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)``

**Comment by GickThomas** [comment]
> > 参考：[https](https://hogwarts.blog/archives/94.html) : [//hogwarts.blog/archives/94.html](https://hogwarts.blog/archives/94.html)
> 
> `02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)`
服务端60000端口干嘛用了，搭建服务了么。

**Comment by 669800** [comment]
> > > 参考：[https](https://hogwarts.blog/archives/94.html) : [//hogwarts.blog/archives/94.html](https://hogwarts.blog/archives/94.html)
> > 
> > `02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)`
> 服务端60000端口干嘛用了，搭建服务了么。

socks5代理

**Comment by 669800** [comment]
> > > > 参考：[https](https://hogwarts.blog/archives/94.html) : [//hogwarts.blog/archives/94.html](https://hogwarts.blog/archives/94.html)
> > > 
> > > `02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)`
> > 服务端60000端口干嘛用了，搭建服务了么。
> 
> socks5代理

我的意思是trojan-r必须通过本地的socks5代理才能联网

**Comment by GickThomas** [comment]
> > > > > 参考：[https](https://hogwarts.blog/archives/94.html) : [//hogwarts.blog/archives/94.html](https://hogwarts.blog/archives/94.html)
> > > > 
> > > > 
> > > > `02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)`
> > > > 服务端60000端口干嘛用了，搭建服务了么。
> > 
> > 
> > socks5代理
> 
> 我的意思是trojan-r必须通过本地的socks5代理才能联网

您的描述超出了我的认知范围，作者的toml链接如下
https://github.com/p4gefau1t/trojan-r/blob/main/config/forward.toml

**Comment by 669800** [comment]
> > > > > > 参考：[https](https://hogwarts.blog/archives/94.html) : [//hogwarts.blog/archives/94.html](https://hogwarts.blog/archives/94.html)
> > > > > 
> > > > > 
> > > > > `02:13Z ERROR trojan_r::proxy] failed to relay tcp stream to 127.0.0.1:60000: Connection timed out (os error 110)`
> > > > > 服务端60000端口干嘛用了，搭建服务了么。
> > > 
> > > 
> > > socks5代理
> > 
> > 我的意思是trojan-r必须通过本地的socks5代理才能联网
> 
> 您的描述超出了我的认知范围，作者的toml链接如下
> https://github.com/p4gefau1t/trojan-r/blob/main/config/forward.toml

我看了，示例是使用DNS转发为模型

**Comment by qiuzi** [comment]
试试ip2socks工具进行nat

**Comment by 669800** [comment]
> 试试ip2socks工具进行nat

具体有没有相关文档？

**Comment by qiuzi** [comment]
https://github.com/zfl9/ipt2socks


ipt2socks -s socks5ip -p 60000 -R -l 443


[tls]
addr = "127.0.0.1:443"  #指向VPS的域名和端口
sni = "服务端域名"

**Comment by 669800** [comment]
> https://github.com/zfl9/ipt2socks
> 
> 
> ipt2socks -s socks5ip -p 60000 -R -l 443
> 
> 
> [tls]
> addr = "127.0.0.1:443"  #指向VPS的域名和端口
> sni = "服务端域名" 

[tls]
addr = "1.0.0.1:443"
sni = "fangb.xyz"
[websocket]
uri = "wss://fangbi.xyz/dnc"

**Comment by qiuzi** [comment]
1.0.0.1是你本地ip吗？

**Comment by 669800** [comment]
> 1.0.0.1是你本地ip吗？

cdn ip地址

**Comment by qiuzi** [comment]
ipt2socks -s socks5ip -p 60000 -R -b 0.0.0.0 -l 443
需要用到iptables redirect 1.0.0.1 到443

**Comment by 669800** [comment]
> ipt2socks -s socks5ip -p 60000 -R -b 0.0.0.0 -l 443
> 需要用到iptables redirect 1.0.0.1 到443

iptables 规则？

**Comment by 669800** [comment]
> > ipt2socks -s socks5ip -p 60000 -R -b 0.0.0.0 -l 443
> > 需要用到iptables redirect 1.0.0.1 到443
> 
> iptables 规则？

ipt2socks和iptables都要用到，感觉有些复杂了，gost链式代理能实现吗？

**Comment by 669800** [comment]
> ipt2socks -s socks5ip -p 60000 -R -b 0.0.0.0 -l 443
> 需要用到iptables redirect 1.0.0.1 到443

可以把iptables规则贴下吗？我学习一下🙏

**Comment by qiuzi** [comment]
gost -L rtcp://0.0.0.0:443/1.0.0.1：443 -F socks5://ip:60000?mbind=true

**Comment by 669800** [comment]
> gost -L rtcp://0.0.0.0:443/1.0.0.1:443 -F socks5://ip:60000?mbind=true

ipt2socks可以不用了吗？

**Comment by qiuzi** [comment]
都可以  看你需求决定 gost我没用过不了解具体功能
