### ISSUE TITLE
您好,打算啥时候支持ssa

### ISSUE THREAD

**Issue by KeyonYe** [p4gefau1t/trojan-r#9]
如题

**Comment by DuckSoft** [comment]
您好，请问“ssa”具体指的是什么呢？

**Comment by KeyonYe** [comment]
> 您好，请问“ssa”具体指的是什么呢？

trojan-go的shadowsock aead

**Comment by 669800** [comment]
> > 您好，请问“ssa”具体指的是什么呢？
> 
> trojan-go的shadowsock aead

不支持任何第三方加密插件.这完全和trojan-go分开了

**Comment by 669800** [comment]
> 如题

trojan-go已经支持了啊，作者吃饱了没事干重复造轮干嘛呢。你说是不是？是不是？
